create
or replace temporary view HEADER_IP as
select
    a.TMSIS_RUN_ID,
    a.TMSIS_ACTV_IND,
    upper(a.SECT_1115A_DEMO_IND) as sect_1115a_demo_ind,
    coalesce(a.ADJDCTN_DT, to_date('01JAN1960')) as ADJDCTN_DT,
    COALESCE(upper(a.ADJSTMT_IND), 'X') AS ADJSTMT_IND,
    upper(a.ADJSTMT_RSN_CD) as adjstmt_rsn_cd,
    a.ADMSN_DT,
    upper(a.ADMSN_HR_NUM) as admsn_hr_num,
    upper(a.ADMSN_TYPE_CD) as admsn_type_cd,
    trim(translate(upper(a.ADMTG_DGNS_CD), '.', '')) as admtg_dgns_cd,
    upper(a.ADMTG_DGNS_CD_IND) as admtg_dgns_cd_ind,
    upper(a.ADMTG_PRVDR_NPI_NUM) as admtg_prvdr_npi_num,
    upper(a.ADMTG_PRVDR_NUM) as admtg_prvdr_num,
    upper(a.ADMTG_PRVDR_SPCLTY_CD) as admtg_prvdr_spclty_cd,
    upper(a.ADMTG_PRVDR_TXNMY_CD) as admtg_prvdr_txnmy_cd,
    upper(a.ADMTG_PRVDR_TYPE_CD) as admtg_prvdr_type_cd,
    a.BENE_COINSRNC_AMT,
    a.BENE_COPMT_AMT,
    a.BENE_DDCTBL_AMT,
    upper(a.BLG_PRVDR_NPI_NUM) as blg_prvdr_npi_num,
    upper(a.BLG_PRVDR_NUM) as blg_prvdr_num,
    upper(a.BLG_PRVDR_SPCLTY_CD) as blg_prvdr_spclty_cd,
    upper(a.BLG_PRVDR_TXNMY_CD) as blg_prvdr_txnmy_cd,
    upper(a.BLG_PRVDR_TYPE_CD) as blg_prvdr_type_cd,
    a.BIRTH_WT_GRMS_QTY,
    upper(a.BRDR_STATE_IND) as brdr_state_ind,
    a.CLL_CNT,
    upper(a.CLM_STUS_CD) as clm_stus_cd,
    upper(a.COPAY_WVD_IND) as copay_wvd_ind,
    upper(a.XOVR_IND) as xovr_ind,
    a.BIRTH_DT,
    trim(translate(upper(a.DGNS_1_CD), '.', '')) as dgns_1_cd,
    trim(translate(upper(a.DGNS_10_CD), '.', '')) as dgns_10_cd,
    trim(translate(upper(a.DGNS_11_CD), '.', '')) as dgns_11_cd,
    trim(translate(upper(a.DGNS_12_CD), '.', '')) as dgns_12_cd,
    trim(translate(upper(a.DGNS_2_CD), '.', '')) as dgns_2_cd,
    trim(translate(upper(a.DGNS_3_CD), '.', '')) as dgns_3_cd,
    trim(translate(upper(a.DGNS_4_CD), '.', '')) as dgns_4_cd,
    trim(translate(upper(a.DGNS_5_CD), '.', '')) as dgns_5_cd,
    trim(translate(upper(a.DGNS_6_CD), '.', '')) as dgns_6_cd,
    trim(translate(upper(a.DGNS_7_CD), '.', '')) as dgns_7_cd,
    trim(translate(upper(a.DGNS_8_CD), '.', '')) as dgns_8_cd,
    trim(translate(upper(a.DGNS_9_CD), '.', '')) as dgns_9_cd,
    upper(a.DGNS_1_CD_IND) as dgns_1_cd_ind,
    upper(a.DGNS_10_CD_IND) as dgns_10_cd_ind,
    upper(a.DGNS_11_CD_IND) as dgns_11_cd_ind,
    upper(a.DGNS_12_CD_IND) as dgns_12_cd_ind,
    upper(a.DGNS_2_CD_IND) as dgns_2_cd_ind,
    upper(a.DGNS_3_CD_IND) as dgns_3_cd_ind,
    upper(a.DGNS_4_CD_IND) as dgns_4_cd_ind,
    upper(a.DGNS_5_CD_IND) as dgns_5_cd_ind,
    upper(a.DGNS_6_CD_IND) as dgns_6_cd_ind,
    upper(a.DGNS_7_CD_IND) as dgns_7_cd_ind,
    upper(a.DGNS_8_CD_IND) as dgns_8_cd_ind,
    upper(a.DGNS_9_CD_IND) as dgns_9_cd_ind,
    upper(a.DGNS_POA_1_CD_IND) as dgns_poa_1_cd_ind,
    upper(a.DGNS_POA_10_CD_IND) as dgns_poa_10_cd_ind,
    upper(a.DGNS_POA_11_CD_IND) as dgns_poa_11_cd_ind,
    upper(a.DGNS_POA_12_CD_IND) as dgns_poa_12_cd_ind,
    upper(a.DGNS_POA_2_CD_IND) as dgns_poa_2_cd_ind,
    upper(a.DGNS_POA_3_CD_IND) as dgns_poa_3_cd_ind,
    upper(a.DGNS_POA_4_CD_IND) as dgns_poa_4_cd_ind,
    upper(a.DGNS_POA_5_CD_IND) as dgns_poa_5_cd_ind,
    upper(a.DGNS_POA_6_CD_IND) as dgns_poa_6_cd_ind,
    upper(a.DGNS_POA_7_CD_IND) as dgns_poa_7_cd_ind,
    upper(a.DGNS_POA_8_CD_IND) as dgns_poa_8_cd_ind,
    upper(a.DGNS_POA_9_CD_IND) as dgns_poa_9_cd_ind,
    upper(a.DRG_CD) as drg_cd,
    upper(a.DRG_CD_IND) as drg_cd_ind,
    case
        when a.DSCHRG_DT is not null then a.DSCHRG_DT
        else null
    end as SRVC_ENDG_DT_DRVD_H,
    case
        when a.DSCHRG_DT is not null then '1'
        else null
    end as SRVC_ENDG_DT_CD_H,
    coalesce(a.DSCHRG_DT, '01JAN1960') as DSCHRG_DT,
    upper(a.DSCHRG_HR_NUM) as dschrg_hr_num,
    upper(a.DRG_DESC) as drg_desc,
    a.DRG_OUTLIER_AMT,
    a.DRG_RLTV_WT_NUM,
    upper(a.ELGBL_1ST_NAME) as elgbl_1st_name,
    upper(a.ELGBL_LAST_NAME) as elgbl_last_name,
    upper(a.ELGBL_MDL_INITL_NAME) as elgbl_mdl_initl_name,
    upper(a.FIXD_PYMT_IND) as fixd_pymt_ind,
    upper(a.FUNDNG_CD) as fundng_cd,
    upper(a.FUNDNG_SRC_NON_FED_SHR_CD) as fundng_src_non_fed_shr_cd,
    upper(a.HLTH_CARE_ACQRD_COND_CD) as hlth_care_acqrd_cond_cd,
    coalesce(upper(a.ADJSTMT_CLM_NUM), '~') as ADJSTMT_CLM_NUM,
    coalesce(upper(a.ORGNL_CLM_NUM), '~') as ORGNL_CLM_NUM,
    a.MDCD_DSH_PD_AMT,
    a.MDCD_CVRD_IP_DAYS_CNT,
    a.MDCD_PD_DT,
    upper(a.MDCR_BENE_ID) as mdcr_bene_id,
    upper(a.MDCR_CMBND_DDCTBL_IND) as mdcr_cmbnd_ddctbl_ind,
    upper(a.MDCR_HICN_NUM) as mdcr_hicn_num,
    a.MDCR_PD_AMT,
    upper(a.MDCR_REIMBRSMT_TYPE_CD) as mdcr_reimbrsmt_type_cd,
    upper(a.MSIS_IDENT_NUM) as msis_ident_num,
    cast(a.NCVRD_CHRGS_AMT as decimal(13, 2)) as NCVRD_CHRGS_AMT,
    a.NCVRD_DAYS_CNT,
    upper(a.OCRNC_01_CD) as ocrnc_01_cd,
    upper(a.OCRNC_02_CD) as ocrnc_02_cd,
    upper(a.OCRNC_03_CD) as ocrnc_03_cd,
    upper(a.OCRNC_04_CD) as ocrnc_04_cd,
    upper(a.OCRNC_05_CD) as ocrnc_05_cd,
    upper(a.OCRNC_06_CD) as ocrnc_06_cd,
    upper(a.OCRNC_07_CD) as ocrnc_07_cd,
    upper(a.OCRNC_08_CD) as ocrnc_08_cd,
    upper(a.OCRNC_09_CD) as ocrnc_09_cd,
    upper(a.OCRNC_10_CD) as ocrnc_10_cd,
    a.OCRNC_01_CD_EFCTV_DT,
    a.OCRNC_02_CD_EFCTV_DT,
    a.OCRNC_03_CD_EFCTV_DT,
    a.OCRNC_04_CD_EFCTV_DT,
    a.OCRNC_05_CD_EFCTV_DT,
    a.OCRNC_06_CD_EFCTV_DT,
    a.OCRNC_07_CD_EFCTV_DT,
    a.OCRNC_08_CD_EFCTV_DT,
    a.OCRNC_09_CD_EFCTV_DT,
    a.OCRNC_10_CD_EFCTV_DT,
    a.OCRNC_01_CD_END_DT,
    a.OCRNC_02_CD_END_DT,
    a.OCRNC_03_CD_END_DT,
    a.OCRNC_04_CD_END_DT,
    a.OCRNC_05_CD_END_DT,
    a.OCRNC_06_CD_END_DT,
    a.OCRNC_07_CD_END_DT,
    a.OCRNC_08_CD_END_DT,
    a.OCRNC_09_CD_END_DT,
    a.OCRNC_10_CD_END_DT,
    upper(a.OTHR_INSRNC_IND) as othr_insrnc_ind,
    upper(a.OTHR_TPL_CLCTN_CD) as othr_tpl_clctn_cd,
    upper(a.OUTLIER_CD) as outlier_cd,
    a.OUTLIER_DAYS_CNT,
    upper(a.PTNT_CNTL_NUM) as ptnt_cntl_num,
    upper(a.PTNT_STUS_CD) as ptnt_stus_cd,
    upper(a.PYMT_LVL_IND) as pymt_lvl_ind,
    upper(a.PLAN_ID_NUM) as mc_plan_id,
    upper(a.PRCDR_1_CD) as prcdr_1_cd,
    upper(a.PRCDR_2_CD) as prcdr_2_cd,
    upper(a.PRCDR_3_CD) as prcdr_3_cd,
    upper(a.PRCDR_4_CD) as prcdr_4_cd,
    upper(a.PRCDR_5_CD) as prcdr_5_cd,
    upper(a.PRCDR_6_CD) as prcdr_6_cd,
    a.PRCDR_1_CD_DT,
    a.PRCDR_2_CD_DT,
    a.PRCDR_3_CD_DT,
    a.PRCDR_4_CD_DT,
    a.PRCDR_5_CD_DT,
    a.PRCDR_6_CD_DT,
    upper(a.PRCDR_1_CD_IND) as prcdr_1_cd_ind,
    upper(a.PRCDR_2_CD_IND) as prcdr_2_cd_ind,
    upper(a.PRCDR_3_CD_IND) as prcdr_3_cd_ind,
    upper(a.PRCDR_4_CD_IND) as prcdr_4_cd_ind,
    upper(a.PRCDR_5_CD_IND) as prcdr_5_cd_ind,
    upper(a.PRCDR_6_CD_IND) as prcdr_6_cd_ind,
    upper(a.PGM_TYPE_CD) as pgm_type_cd,
    upper(a.PRVDR_LCTN_ID) as prvdr_lctn_id,
    upper(a.RFRG_PRVDR_NPI_NUM) as rfrg_prvdr_npi_num,
    upper(a.RFRG_PRVDR_NUM) as rfrg_prvdr_num,
    upper(a.RFRG_PRVDR_SPCLTY_CD) as rfrg_prvdr_spclty_cd,
    upper(a.RFRG_PRVDR_TXNMY_CD) as rfrg_prvdr_txnmy_cd,
    upper(a.RFRG_PRVDR_TYPE_CD) as rfrg_prvdr_type_cd,
    a.SRVC_TRKNG_PYMT_AMT,
    upper(a.SRVC_TRKNG_TYPE_CD) as srvc_trkng_type_cd,
    upper(a.SPLIT_CLM_IND) as split_clm_ind,
    a.SUBMTG_STATE_CD,
    a.TOT_ALOWD_AMT,
    a.TOT_BILL_AMT,
    a.TOT_COPAY_AMT,
    a.TOT_MDCD_PD_AMT,
    a.TOT_MDCR_COINSRNC_AMT,
    a.TOT_MDCR_DDCTBL_AMT,
    a.TOT_OTHR_INSRNC_AMT,
    a.TOT_TPL_AMT,
    upper(a.BILL_TYPE_CD) as bill_type_cd,
    upper(a.CLM_TYPE_CD) as clm_type_cd,
    upper(a.HOSP_TYPE_CD) as hosp_type_cd,
    upper(a.WVR_ID) as wvr_id,
    upper(a.WVR_TYPE_CD) as wvr_type_cd,
    a.TP_COINSRNC_PD_AMT,
    a.TP_COPMT_PD_AMT,
    case
        when DSCHRG_DT is NULL then 1
        else 0
    end as NO_DISCH_DT
from
    cms_prod.TMSIS_CLH_REC_IP A
where
    (
        (
            date_part_year (DSCHRG_DT) = 2021
            and date_part (month, DSCHRG_DT) = 10
        )
        or DSCHRG_DT is NULL
    )
    and A.TMSIS_ACTV_IND = 1
    and (
        upper(A.CLM_STUS_CTGRY_CD) <> 'F2'
        or A.CLM_STUS_CTGRY_CD is null
    )
    and (
        upper(A.CLM_TYPE_CD) <> 'Z'
        or A.CLM_TYPE_CD is null
    )
    and (
        A.CLM_DND_IND <> '0'
        or A.CLM_DND_IND is null
    )
    and (
        A.CLM_STUS_CD NOT IN('26', '87', '026', '087', '542', '585', '654')
        or A.CLM_STUS_CD is null
    )
    and (
        A.ADJSTMT_IND <> '1'
        or A.ADJSTMT_IND IS NULL
    )
    and (a.submtg_state_cd, a.tmsis_run_id) in (
        concat('01', 4574),
        concat('02', 4567),
        concat('04', 4554),
        concat('05', 4550),
        concat('06', 4556),
        concat('08', 4578),
        concat('09', 4568),
        concat('10', 4557),
        concat('11', 4545),
        concat('12', 4555),
        concat('13', 4538),
        concat('15', 4558),
        concat('16', 4579),
        concat('17', 4584),
        concat('18', 4561),
        concat('19', 4548),
        concat('20', 4589),
        concat('21', 4553),
        concat('22', 4573),
        concat('23', 4540),
        concat('24', 4569),
        concat('25', 4559),
        concat('26', 4585),
        concat('27', 4539),
        concat('28', 4594),
        concat('29', 4562),
        concat('30', 4580),
        concat('31', 4546),
        concat('32', 4551),
        concat('33', 4570),
        concat('34', 4590),
        concat('35', 4552),
        concat('36', 4566),
        concat('37', 4517),
        concat('38', 4575),
        concat('39', 4571),
        concat('40', 4593),
        concat('41', 4541),
        concat('42', 4560),
        concat('44', 4592),
        concat('45', 4544),
        concat('46', 4549),
        concat('47', 4583),
        concat('48', 4507),
        concat('49', 4577),
        concat('50', 4581),
        concat('51', 4564),
        concat('53', 4587),
        concat('54', 4582),
        concat('55', 4565),
        concat('56', 4423),
        concat('72', 4547),
        concat('78', 4563),
        concat('93', 4447),
        concat('97', 4543)
    )
