create temp table LT_HEADER distkey (ORGNL_CLM_NUM) sortkey (
    NEW_SUBMTG_STATE_CD,
    ORGNL_CLM_NUM,
    ADJSTMT_CLM_NUM,
    ADJDCTN_DT,
    ADJSTMT_IND
) as
select
    HEADER.*,
    coalesce(CONSTR.NUM_CLL, 0) as NUM_CLL,
    CONSTR.ACCOMMODATION_PAID,
    CONSTR.ANCILLARY_PAID,
    case
        when CONSTR.MH_DAYS_OVER_65 = 1 then HEADER.MDCD_CVRD_IP_DAYS_CNT
        when CONSTR.MH_DAYS_OVER_65 = 0
        and HEADER.MDCD_CVRD_IP_DAYS_CNT is not null then 0
    end as CVRD_MH_DAYS_OVER_65,
    case
        when CONSTR.MH_DAYS_UNDER_21 = 1 then HEADER.MDCD_CVRD_IP_DAYS_CNT
        when CONSTR.MH_DAYS_UNDER_21 = 0
        and HEADER.MDCD_CVRD_IP_DAYS_CNT is not null then 0
    end as CVRD_MH_DAYS_UNDER_21
from
    FA_HDR_LT HEADER
    left join constructed_LT CONSTR on HEADER.NEW_SUBMTG_STATE_CD = CONSTR.NEW_SUBMTG_STATE_CD_LINE
    and HEADER.ORGNL_CLM_NUM = CONSTR.ORGNL_CLM_NUM_LINE
    and HEADER.ADJSTMT_CLM_NUM = CONSTR.ADJSTMT_CLM_NUM_LINE
    and HEADER.ADJDCTN_DT = CONSTR.ADJDCTN_DT_LINE
    and HEADER.ADJSTMT_IND = CONSTR.LINE_ADJSTMT_IND