create temp TABLE ALL_HEADER_RX distkey(ORGNL_CLM_NUM) sortkey(
    TMSIS_RUN_ID,
    SUBMTG_STATE_CD,
    ORGNL_CLM_NUM,
    ADJSTMT_CLM_NUM,
    ADJDCTN_DT,
    ADJSTMT_IND
) as
select
    H.*
from
    HEADER2_RX H
    inner join CLM_FMLY_RX F on H.ORGNL_CLM_NUM = F.ORGNL_CLM_NUM
    and H.ADJSTMT_CLM_NUM = F.ADJSTMT_CLM_NUM
    and H.ADJDCTN_DT = F.ADJDCTN_DT
    and H.ADJSTMT_IND = F.ADJSTMT_IND
    and H.SUBMTG_STATE_CD = F.SUBMTG_STATE_CD
    and H.TMSIS_RUN_ID = F.TMSIS_RUN_ID