create temp table OT_LINE_IN distkey (ORGNL_CLM_NUM_LINE) sortkey (
    SUBMTG_STATE_CD,
    ORGNL_CLM_NUM_LINE,
    ADJSTMT_CLM_NUM_LINE,
    ADJDCTN_DT_LINE,
    LINE_ADJSTMT_IND
) as
select
    SUBMTG_STATE_CD,
    a.TMSIS_FIL_NAME,
    a.REC_NUM,
    a.TMSIS_RUN_ID as TMSIS_RUN_ID_LINE,
    coalesce(a.ADJDCTN_DT, '01JAN1960') AS ADJDCTN_DT_LINE,
    a.ALOWD_AMT,
    coalesce(a.SRVC_BGNNG_DT, '01JAN1960') as SRVC_BGNNG_DT_LINE,
    upper(a.BNFT_TYPE_CD) as bnft_type_cd,
    a.BILL_AMT,
    upper(a.CLL_STUS_CD) as cll_stus_cd,
    upper(a.CMS_64_FED_REIMBRSMT_CTGRY_CD) as cms_64_fed_reimbrsmt_ctgry_cd,
    a.COPAY_AMT,
    coalesce(a.SRVC_ENDG_DT, '01JAN1960') as SRVC_ENDG_DT_LINE,
    upper(a.HCPCS_SRVC_CD) as HCBS_SRVC_CD,
    upper(a.HCPCS_TXNMY_CD) as HCBS_TXNMY,
    upper(a.HCPCS_RATE) as hcpcs_rate,
    coalesce(upper(a.ADJSTMT_CLM_NUM), '~') AS ADJSTMT_CLM_NUM_LINE,
    coalesce(upper(a.ORGNL_CLM_NUM), '~') AS ORGNL_CLM_NUM_LINE,
    upper(a.IMNZTN_TYPE_CD) as imnztn_type_cd,
    coalesce(upper(a.LINE_ADJSTMT_IND), 'X') as LINE_ADJSTMT_IND,
    upper(a.ADJSTMT_LINE_RSN_CD) as adjstmt_line_rsn_cd,
    upper(a.ADJSTMT_LINE_NUM) as adjstmt_line_num,
    upper(a.ORGNL_LINE_NUM) as orgnl_line_num,
    a.MDCD_FFS_EQUIV_AMT,
    a.MDCD_PD_AMT,
    a.MDCR_PD_AMT,
    upper(a.MSIS_IDENT_NUM) as MSIS_IDENT_NUM_LINE,
    upper(a.NDC_CD) as ndc_cd,
    a.NDC_QTY,
    upper(a.NDC_UOM_CD) as uom_cd,
    a.OTHR_TOC_RX_CLM_ACTL_QTY,
    a.OTHR_TOC_RX_CLM_ALOWD_QTY,
    a.OTHR_INSRNC_AMT,
    upper(a.PRE_AUTHRZTN_NUM) as pre_authrztn_num,
    upper(a.PRCDR_CD) as prcdr_cd,
    a.PRCDR_CD_DT,
    upper(a.PRCDR_CD_IND) as prcdr_cd_ind,
    upper(a.PRCDR_1_MDFR_CD) as prcdr_1_mdfr_cd,
    upper(a.PRCDR_2_MDFR_CD) as prcdr_2_mdfr_cd,
    upper(a.PRCDR_3_MDFR_CD) as prcdr_3_mdfr_cd,
    upper(a.PRCDR_4_MDFR_CD) as prcdr_4_mdfr_cd,
    upper(a.REV_CD) as rev_cd,
    upper(a.SELF_DRCTN_TYPE_CD) as self_drctn_type_cd,
    upper(a.PRSCRBNG_PRVDR_NPI_NUM) as prscrbng_prvdr_npi_num,
    upper(a.SRVCNG_PRVDR_NUM) as srvcng_prvdr_num,
    upper(a.SRVCNG_PRVDR_SPCLTY_CD) as srvcng_prvdr_spclty_cd,
    upper(a.SRVCNG_PRVDR_TXNMY_CD) as srvcng_prvdr_txnmy_cd,
    upper(a.SRVCNG_PRVDR_TYPE_CD) as srvcng_prvdr_type_cd,
    upper(a.STATE_NOTN_TXT) as state_notn_txt,
    a.SUBMTG_STATE_CD as SUBMTG_STATE_CD_LINE,
    upper(a.TOOTH_DSGNTN_SYS_CD) as tooth_dsgntn_sys_cd,
    upper(a.TOOTH_NUM) as tooth_num,
    upper(a.TOOTH_ORAL_CVTY_AREA_DSGNTD_CD) as tooth_oral_cvty_area_dsgntd_cd,
    upper(a.TOOTH_SRFC_CD) as tooth_srfc_cd,
    a.TPL_AMT,
    upper(a.STC_CD) as tos_cd,
    upper(lpad(trim(a.XIX_SRVC_CTGRY_CD), 4, '0')) as XIX_SRVC_CTGRY_CD,
    upper(lpad(trim(a.XXI_SRVC_CTGRY_CD), 3, '0')) as XXI_SRVC_CTGRY_CD
from
    cms_prod.TMSIS_CLL_REC_OTHR_TOC A
where
    A.TMSIS_ACTV_IND = 1
    and a.submtg_state_cd = '01'
    and a.tmsis_run_id = 4684