create temp table HEADER_LT distkey(ORGNL_CLM_NUM) sortkey(
    TMSIS_RUN_ID,
    SUBMTG_STATE_CD,
    ORGNL_CLM_NUM,
    ADJSTMT_CLM_NUM,
    ADJDCTN_DT,
    ADJSTMT_IND
) as
select
    a.TMSIS_RUN_ID,
    upper(a.TMSIS_FIL_NAME) as tmsis_fil_name,
    a.TMSIS_ACTV_IND,
    upper(a.SECT_1115A_DEMO_IND) as sect_1115a_demo_ind,
    coalesce(a.ADJDCTN_DT, '01JAN1960') as ADJDCTN_DT,
    coalesce(upper(a.ADJSTMT_IND), 'X') AS ADJSTMT_IND,
    upper(a.ADJSTMT_RSN_CD) as adjstmt_rsn_cd,
    a.ADMSN_DT,
    upper(a.ADMSN_HR_NUM) as admsn_hr_num,
    trim(translate(upper(a.ADMTG_DGNS_CD), '.', '')) as admtg_dgns_cd,
    upper(a.ADMTG_DGNS_CD_IND) as admtg_dgns_cd_ind,
    upper(a.ADMTG_PRVDR_NPI_NUM) as admtg_prvdr_npi_num,
    upper(a.ADMTG_PRVDR_NUM) as admtg_prvdr_num,
    upper(a.ADMTG_PRVDR_SPCLTY_CD) as admtg_prvdr_spclty_cd,
    upper(a.ADMTG_PRVDR_TXNMY_CD) as admtg_prvdr_txnmy_cd,
    upper(a.ADMTG_PRVDR_TYPE_CD) as admtg_prvdr_type_cd,
    a.SRVC_BGNNG_DT,
    a.BENE_COINSRNC_AMT,
    a.BENE_COINSRNC_PD_DT,
    a.BENE_COPMT_AMT,
    a.BENE_COPMT_PD_DT,
    a.BENE_DDCTBL_AMT,
    a.BENE_DDCTBL_PD_DT,
    upper(a.BLG_PRVDR_NPI_NUM) as blg_prvdr_npi_num,
    upper(a.BLG_PRVDR_NUM) as blg_prvdr_num,
    upper(a.BLG_PRVDR_SPCLTY_CD) as blg_prvdr_spclty_cd,
    upper(a.BLG_PRVDR_TXNMY_CD) as blg_prvdr_txnmy_cd,
    upper(a.BLG_PRVDR_TYPE_CD) as blg_prvdr_type_cd,
    upper(a.BRDR_STATE_IND) as brdr_state_ind,
    a.CHK_EFCTV_DT,
    upper(a.CHK_NUM) as chk_num,
    upper(a.CLM_DND_IND) as clm_dnd_ind,
    a.CLL_CNT,
    upper(a.CLM_PYMT_REMIT_1_CD) as clm_pymt_remit_1_cd,
    upper(a.CLM_PYMT_REMIT_2_CD) as clm_pymt_remit_2_cd,
    upper(a.CLM_PYMT_REMIT_3_CD) as clm_pymt_remit_3_cd,
    upper(a.CLM_PYMT_REMIT_4_CD) as clm_pymt_remit_4_cd,
    upper(a.CLM_STUS_CD) as clm_stus_cd,
    upper(a.CLM_STUS_CTGRY_CD) as clm_stus_ctgry_cd,
    upper(a.COPAY_WVD_IND) as copay_wvd_ind,
    upper(a.XOVR_IND) as xovr_ind,
    a.DAILY_RATE,
    a.BIRTH_DT,
    trim(translate(upper(a.DGNS_1_CD), '.', '')) as dgns_1_cd,
    trim(translate(upper(a.DGNS_2_CD), '.', '')) as dgns_2_cd,
    trim(translate(upper(a.DGNS_3_CD), '.', '')) as dgns_3_cd,
    trim(translate(upper(a.DGNS_4_CD), '.', '')) as dgns_4_cd,
    trim(translate(upper(a.DGNS_5_CD), '.', '')) as dgns_5_cd,
    upper(a.DGNS_1_CD_IND) as dgns_1_cd_ind,
    upper(a.DGNS_2_CD_IND) as dgns_2_cd_ind,
    upper(a.DGNS_3_CD_IND) as dgns_3_cd_ind,
    upper(a.DGNS_4_CD_IND) as dgns_4_cd_ind,
    upper(a.DGNS_5_CD_IND) as dgns_5_cd_ind,
    upper(a.DGNS_POA_1_CD_IND) as dgns_poa_1_cd_ind,
    upper(a.DGNS_POA_2_CD_IND) as dgns_poa_2_cd_ind,
    upper(a.DGNS_POA_3_CD_IND) as dgns_poa_3_cd_ind,
    upper(a.DGNS_POA_4_CD_IND) as dgns_poa_4_cd_ind,
    upper(a.DGNS_POA_5_CD_IND) as dgns_poa_5_cd_ind,
    a.DSCHRG_DT,
    upper(a.DSCHRG_HR_NUM) as dschrg_hr_num,
    upper(a.ELGBL_1ST_NAME) as elgbl_1st_name,
    upper(a.ELGBL_LAST_NAME) as elgbl_last_name,
    upper(a.ELGBL_MDL_INITL_NAME) as elgbl_mdl_initl_name,
    coalesce(a.SRVC_ENDG_DT, '01JAN1960') as SRVC_ENDG_DT,
    upper(a.FIXD_PYMT_IND) as fixd_pymt_ind,
    upper(a.FRCD_CLM_CD) as frcd_clm_cd,
    upper(a.FUNDNG_CD) as fundng_cd,
    upper(a.FUNDNG_SRC_NON_FED_SHR_CD) as fundng_src_non_fed_shr_cd,
    upper(a.HLTH_CARE_ACQRD_COND_CD) as hlth_care_acqrd_cond_cd,
    upper(a.HH_ENT_NAME) as hh_ent_name,
    upper(a.HH_PRVDR_IND) as hh_prvdr_ind,
    upper(a.HH_PRVDR_NPI_NUM) as hh_prvdr_npi_num,
    a.ICF_IID_DAYS_CNT,
    coalesce(upper(a.ADJSTMT_CLM_NUM), '~') AS ADJSTMT_CLM_NUM,
    coalesce(upper(a.ORGNL_CLM_NUM), '~') AS ORGNL_CLM_NUM,
    a.LVE_DAYS_CNT,
    a.LTC_RCP_LBLTY_AMT,
    case
        when a.MDCD_CVRD_IP_DAYS_CNT = 88888 then null
        else a.MDCD_CVRD_IP_DAYS_CNT
    end as MDCD_CVRD_IP_DAYS_CNT,
    a.MDCD_PD_DT,
    upper(a.MDCR_BENE_ID) as mdcr_bene_id,
    upper(a.MDCR_CMBND_DDCTBL_IND) as mdcr_cmbnd_ddctbl_ind,
    upper(a.MDCR_HICN_NUM) as mdcr_hicn_num,
    a.MDCR_PD_AMT,
    upper(a.MDCR_REIMBRSMT_TYPE_CD) as mdcr_reimbrsmt_type_cd,
    upper(a.MSIS_IDENT_NUM) as msis_ident_num,
    upper(a.NATL_HLTH_CARE_ENT_ID) as natl_hlth_care_ent_id,
    a.NCVRD_CHRGS_AMT,
    a.NCVRD_DAYS_CNT,
    a.NRSNG_FAC_DAYS_CNT,
    upper(a.OCRNC_01_CD) as ocrnc_01_cd,
    upper(a.OCRNC_02_CD) as ocrnc_02_cd,
    upper(a.OCRNC_03_CD) as ocrnc_03_cd,
    upper(a.OCRNC_04_CD) as ocrnc_04_cd,
    upper(a.OCRNC_05_CD) as ocrnc_05_cd,
    upper(a.OCRNC_06_CD) as ocrnc_06_cd,
    upper(a.OCRNC_07_CD) as ocrnc_07_cd,
    upper(a.OCRNC_08_CD) as ocrnc_08_cd,
    upper(a.OCRNC_09_CD) as ocrnc_09_cd,
    upper(a.OCRNC_10_CD) as ocrnc_10_cd,
    a.OCRNC_01_CD_EFCTV_DT,
    a.OCRNC_02_CD_EFCTV_DT,
    a.OCRNC_03_CD_EFCTV_DT,
    a.OCRNC_04_CD_EFCTV_DT,
    a.OCRNC_05_CD_EFCTV_DT,
    a.OCRNC_06_CD_EFCTV_DT,
    a.OCRNC_07_CD_EFCTV_DT,
    a.OCRNC_08_CD_EFCTV_DT,
    a.OCRNC_09_CD_EFCTV_DT,
    a.OCRNC_10_CD_EFCTV_DT,
    a.OCRNC_01_CD_END_DT,
    a.OCRNC_02_CD_END_DT,
    a.OCRNC_03_CD_END_DT,
    a.OCRNC_04_CD_END_DT,
    a.OCRNC_05_CD_END_DT,
    a.OCRNC_06_CD_END_DT,
    a.OCRNC_07_CD_END_DT,
    a.OCRNC_08_CD_END_DT,
    a.OCRNC_09_CD_END_DT,
    a.OCRNC_10_CD_END_DT,
    upper(a.OTHR_INSRNC_IND) as othr_insrnc_ind,
    upper(a.OTHR_TPL_CLCTN_CD) as othr_tpl_clctn_cd,
    upper(a.PTNT_CNTL_NUM) as ptnt_cntl_num,
    upper(a.PTNT_STUS_CD) as ptnt_stus_cd,
    upper(a.PYMT_LVL_IND) as pymt_lvl_ind,
    upper(a.PLAN_ID_NUM) as mc_plan_id,
    upper(a.PGM_TYPE_CD) as pgm_type_cd,
    a.REC_NUM,
    upper(a.PRVDR_LCTN_ID) as prvdr_lctn_id,
    upper(a.RFRG_PRVDR_NPI_NUM) as rfrg_prvdr_npi_num,
    upper(a.RFRG_PRVDR_NUM) as rfrg_prvdr_num,
    upper(a.RFRG_PRVDR_SPCLTY_CD) as rfrg_prvdr_spclty_cd,
    upper(a.RFRG_PRVDR_TXNMY_CD) as rfrg_prvdr_txnmy_cd,
    upper(a.RFRG_PRVDR_TYPE_CD) as rfrg_prvdr_type_cd,
    upper(a.RMTNC_NUM) as rmtnc_num,
    a.SRVC_TRKNG_PYMT_AMT,
    upper(a.SRVC_TRKNG_TYPE_CD) as srvc_trkng_type_cd,
    upper(a.SRC_LCTN_CD) as src_lctn_cd,
    upper(a.SPLIT_CLM_IND) as split_clm_ind,
    upper(a.STATE_NOTN_TXT) as state_notn_txt,
    upper(a.SBMTR_ID) as sbmtr_id,
    a.SUBMTG_STATE_CD,
    a.TP_COINSRNC_PD_AMT,
    a.TP_COINSRNC_PD_DT,
    a.TP_COPMT_PD_AMT,
    a.TP_COPMT_PD_DT,
    a.TOT_ALOWD_AMT,
    a.TOT_BILL_AMT,
    a.TOT_COPAY_AMT,
    a.TOT_MDCD_PD_AMT,
    a.TOT_MDCR_COINSRNC_AMT,
    a.TOT_MDCR_DDCTBL_AMT,
    a.TOT_OTHR_INSRNC_AMT,
    a.TOT_TPL_AMT,
    upper(a.BILL_TYPE_CD) as bill_type_cd,
    upper(a.CLM_TYPE_CD) as clm_type_cd,
    upper(a.WVR_ID) as wvr_id,
    upper(a.WVR_TYPE_CD) as wvr_type_cd
from
    cms_prod.TMSIS_CLH_REC_LT A
where
    (
        (
            date_part_year (a.SRVC_ENDG_DT) = 2017
            and date_part (month, a.SRVC_ENDG_DT) = 12
        )
    )
    and A.TMSIS_ACTV_IND = 1
    and (
        upper(A.CLM_STUS_CTGRY_CD) <> 'F2'
        or A.CLM_STUS_CTGRY_CD is null
    )
    and (
        upper(A.CLM_TYPE_CD) <> 'Z'
        or A.CLM_TYPE_CD is null
    )
    and (
        A.CLM_DND_IND <> '0'
        or A.CLM_DND_IND is null
    )
    and (
        A.CLM_STUS_CD NOT IN('26', '87', '026', '087', '542', '585', '654')
        or A.CLM_STUS_CD is null
    )
    and (
        A.ADJSTMT_IND <> '1'
        or A.ADJSTMT_IND IS NULL
    )
    and (a.submtg_state_cd, a.tmsis_run_id) in (
        ('01', 4617),
        ('02', 4646),
        ('04', 4663),
        ('05', 4661),
        ('06', 4605),
        ('08', 4629),
        ('09', 4664),
        ('10', 4618),
        ('11', 4662),
        ('12', 4679),
        ('13', 4656),
        ('15', 4667),
        ('16', 4643),
        ('17', 4640),
        ('18', 4681),
        ('19', 4600),
        ('20', 4651),
        ('21', 4666),
        ('22', 4670),
        ('23', 4654),
        ('24', 4682),
        ('25', 4672),
        ('26', 4645),
        ('27', 4652),
        ('28', 4649),
        ('29', 4665),
        ('30', 4632),
        ('31', 4657),
        ('32', 4627),
        ('33', 4620),
        ('34', 4650),
        ('35', 4668),
        ('36', 4635),
        ('37', 4648),
        ('38', 4639),
        ('39', 4624),
        ('40', 4659),
        ('41', 4609),
        ('42', 4671),
        ('44', 4647),
        ('45', 4673),
        ('46', 4603),
        ('47', 4625),
        ('48', 4653),
        ('49', 4655),
        ('50', 4638),
        ('51', 4674),
        ('53', 4642),
        ('54', 4628),
        ('55', 4612),
        ('56', 4423),
        ('72', 4660),
        ('78', 4633),
        ('93', 4447),
        ('97', 4658)
    )