create temp table LT_LINE_IN distkey (ORGNL_CLM_NUM_LINE) sortkey (
    SUBMTG_STATE_CD,
    ORGNL_CLM_NUM_LINE,
    ADJSTMT_CLM_NUM_LINE,
    ADJDCTN_DT_LINE,
    LINE_ADJSTMT_IND
) as
select
    SUBMTG_STATE_CD,
    a.TMSIS_RUN_ID as TMSIS_RUN_ID_LINE,
    a.TMSIS_FIL_NAME,
    a.TMSIS_OFST_BYTE_NUM,
    a.TMSIS_COMT_ID,
    a.TMSIS_DLTD_IND,
    a.TMSIS_OBSLT_IND,
    a.TMSIS_ACTV_IND as TMSIS_ACTV_IND_LINE,
    a.TMSIS_SQNC_NUM,
    a.TMSIS_RUN_TS,
    a.TMSIS_RPTG_PRD,
    a.TMSIS_REC_MD5_B64_TXT,
    a.REC_TYPE_CD,
    coalesce(a.ADJDCTN_DT, '01JAN1960') AS ADJDCTN_DT_LINE,
    a.ALOWD_AMT,
    coalesce(a.SRVC_BGNNG_DT, '01JAN1960') as SRVC_BGNNG_DT,
    upper(a.BNFT_TYPE_CD) as bnft_type_cd,
    upper(a.BLG_UNIT_CD) as blg_unit_cd,
    upper(a.CLL_STUS_CD) as cll_stus_cd,
    upper(a.CMS_64_FED_REIMBRSMT_CTGRY_CD) as cms_64_fed_reimbrsmt_ctgry_cd,
    coalesce(a.SRVC_ENDG_DT, '01JAN1960') as SRVC_ENDG_DT,
    upper(a.HCPCS_RATE) as hcpcs_rate,
    coalesce(upper(a.ADJSTMT_CLM_NUM), '~') AS ADJSTMT_CLM_NUM_LINE,
    coalesce(upper(a.ORGNL_CLM_NUM), '~') AS ORGNL_CLM_NUM_LINE,
    upper(a.IMNZTN_TYPE_CD) as imnztn_type_cd,
    a.IP_LT_ACTL_SRVC_QTY,
    a.IP_LT_ALOWD_SRVC_QTY,
    coalesce(upper(a.LINE_ADJSTMT_IND), 'X') as LINE_ADJSTMT_IND,
    upper(a.ADJSTMT_LINE_RSN_CD) as adjstmt_line_rsn_cd,
    upper(a.ADJSTMT_LINE_NUM) as adjstmt_line_num,
    upper(a.ORGNL_LINE_NUM) as orgnl_line_num,
    a.MDCD_FFS_EQUIV_AMT,
    case
        when a.MDCD_PD_AMT != 888888888.88 then a.MDCD_PD_AMT
        else NULL
    end as MDCD_PD_AMT,
    upper(a.MSIS_IDENT_NUM) as MSIS_IDENT_NUM_LINE,
    upper(a.NDC_CD) as ndc_cd,
    a.NDC_QTY,
    upper(a.NDC_UOM_CD) as uom_cd,
    a.OTHR_INSRNC_AMT,
    upper(a.OTHR_TPL_CLCTN_CD) as othr_tpl_clctn_cd,
    upper(a.PRE_AUTHRZTN_NUM) as pre_authrztn_num,
    upper(a.PRVDR_FAC_TYPE_CD) as prvdr_fac_type_cd,
    a.REC_NUM,
    a.REV_CHRG_AMT,
    upper(a.REV_CD) as rev_cd,
    upper(a.SELF_DRCTN_TYPE_CD) as self_drctn_type_cd,
    upper(a.PRSCRBNG_PRVDR_NPI_NUM) as SRVCNG_PRVDR_NPI_NUM,
    upper(a.SRVCNG_PRVDR_NUM) as srvcng_prvdr_num,
    upper(a.SRVCNG_PRVDR_SPCLTY_CD) as srvcng_prvdr_spclty_cd,
    upper(a.SRVCNG_PRVDR_TXNMY_CD) as srvcng_prvdr_txnmy_cd,
    upper(a.SRVCNG_PRVDR_TYPE_CD) as srvcng_prvdr_type_cd,
    upper(a.STATE_NOTN_TXT) as state_notn_txt,
    upper(a.SBMTR_ID) as sbmtg_id,
    upper(a.SUBMTG_STATE_CD) as SUBMTG_STATE_CD_LINE,
    a.TPL_AMT,
    upper(a.STC_CD) as tos_cd,
    upper(lpad(trim(a.XIX_SRVC_CTGRY_CD), 4, '0')) as XIX_SRVC_CTGRY_CD,
    upper(lpad(trim(a.XXI_SRVC_CTGRY_CD), 3, '0')) as XXI_SRVC_CTGRY_CD
from
    cms_prod.TMSIS_CLL_REC_LT A
where
    A.TMSIS_ACTV_IND = 1
    and (a.submtg_state_cd, a.tmsis_run_id) in (
        ('01', 4617),
        ('02', 4646),
        ('04', 4663),
        ('05', 4661),
        ('06', 4605),
        ('08', 4629),
        ('09', 4664),
        ('10', 4618),
        ('11', 4662),
        ('12', 4679),
        ('13', 4656),
        ('15', 4667),
        ('16', 4643),
        ('17', 4640),
        ('18', 4681),
        ('19', 4600),
        ('20', 4651),
        ('21', 4666),
        ('22', 4670),
        ('23', 4654),
        ('24', 4682),
        ('25', 4672),
        ('26', 4645),
        ('27', 4652),
        ('28', 4649),
        ('29', 4665),
        ('30', 4632),
        ('31', 4657),
        ('32', 4627),
        ('33', 4620),
        ('34', 4650),
        ('35', 4668),
        ('36', 4635),
        ('37', 4648),
        ('38', 4639),
        ('39', 4624),
        ('40', 4659),
        ('41', 4609),
        ('42', 4671),
        ('44', 4647),
        ('45', 4673),
        ('46', 4603),
        ('47', 4625),
        ('48', 4653),
        ('49', 4655),
        ('50', 4638),
        ('51', 4674),
        ('53', 4642),
        ('54', 4628),
        ('55', 4612),
        ('56', 4423),
        ('72', 4660),
        ('78', 4633),
        ('93', 4447),
        ('97', 4658)
    )