from unittest.mock import MagicMock

from taf.DE.DE0006 import DE0006


def test_create_wvr_suppl_table_drops_and_recreates_numbers_two():
    # Mock the runner so the test does not require a Spark session
    runner = MagicMock()
    runner.DA_SCHEMA = "taf_v6"
    runner.YEAR = "2024"

    de0006 = DE0006(runner)

    # Build the SQL statements generated by the method
    de0006.create_wvr_suppl_table()

    # Get the SQL statements passed to the runner
    sql_statements = [call.args[1] for call in runner.append.call_args_list]

    # Find the statements related to numbers_two
    numbers_two_statements = [
        sql for sql in sql_statements if "numbers_two" in sql.lower()
    ]

    # Verify numbers_two is dropped before it is recreated
    assert "drop table if exists taf_v6.numbers_two" in numbers_two_statements[0].lower()

    # Verify numbers_two is created with the expected columns
    assert "create table taf_v6.numbers_two" in numbers_two_statements[1].lower()
    assert "(slot int, month string)" in numbers_two_statements[1].lower()
    assert "using delta" in numbers_two_statements[1].lower()

    # Verify data is inserted into the newly created table
    assert "insert into taf_v6.numbers_two" in numbers_two_statements[2].lower()