from unittest.mock import MagicMock

from taf.DE.DE0002 import DE0002


def test_numbers_drops_and_recreates_numbers_table():
    # Mock the runner so the test does not require a Spark session
    runner = MagicMock()
    runner.DA_SCHEMA = "taf_v6"

    de0002 = DE0002(runner)

    # Build the SQL statements generated by the numbers() method
    de0002.numbers()

    # Get the SQL statements passed to the runner
    sql_statements = [call.args[1] for call in runner.append.call_args_list]

    # Verify the numbers table is dropped before it is recreated
    assert "drop table if exists taf_v6.numbers" in sql_statements[0]

    # Verify the numbers table is created with the expected columns
    assert "create table taf_v6.numbers" in sql_statements[1]
    assert "(slot int, month string)" in sql_statements[1]
    assert "using delta" in sql_statements[1]

    # Verify data is inserted into the newly created table
    assert "insert into taf_v6.numbers" in sql_statements[2]